version: '1'
services:
  webserver:
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID} # from .env
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY} #from .env
    volumes:
      - app-vol:/voldata
    ports:
      - "8088:8088"
volumes:
  app-vol: